[workspace]
release = false
release_always = false

[[package]]
name = "pharia-skill-macros"
release = true

[[package]]
name = "pharia-skill"
release = true

[[package]]
name = "pharia-skill-test"
release = true
