[package]
name = "pharia-skill-test"
description = "Test helpers for testing Pharia Kernel skill components locally."
rust-version = "1.76.0"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
pharia-skill = { path = "../pharia-skill" }
ureq = { version = "2.10.1", features = ["json"] }

[lints]
workspace = true

[dev-dependencies]
dotenvy = "0.15.7"
