name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Publish to crates registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish pharia-skill-macros
        working-directory: ./pharia-skill-macros
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish pharia-skill
        working-directory: ./pharia-skill
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish pharia-skill-test
        working-directory: ./pharia-skill-test
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
