name: Security audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - .github/workflows/security.yml
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@33734a118689b0b418824fb78ea2bf18e970b43b
        with:
          tool: cargo-audit
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      issues: write
      checks: write
